name: Basic Code Review

on:
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm install
      
    - name: Check for test script
      id: check-test
      run: |
        if npm run | grep -q "test"; then
          echo "TEST_SCRIPT_EXISTS=true" >> $GITHUB_OUTPUT
        else
          echo "TEST_SCRIPT_EXISTS=false" >> $GITHUB_OUTPUT
          echo "⚠️ No test script found, skipping tests"
        fi
      
    - name: Run tests (if exists)
      if: steps.check-test.outputs.TEST_SCRIPT_EXISTS == 'true'
      run: npm test
      
    - name: Run tests with coverage (if exists)
      if: steps.check-test.outputs.TEST_SCRIPT_EXISTS == 'true'
      run: npm test -- --coverage --watchAll=false || true
      
    - name: Check for build script
      id: check-build
      run: |
        if npm run | grep -q "build"; then
          echo "BUILD_SCRIPT_EXISTS=true" >> $GITHUB_OUTPUT
        else
          echo "BUILD_SCRIPT_EXISTS=false" >> $GITHUB_OUTPUT
          echo "⚠️ No build script found, skipping build"
        fi
      
    - name: Build project (if exists)
      if: steps.check-build.outputs.BUILD_SCRIPT_EXISTS == 'true'
      run: npm run build
      
    - name: Security audit
      run: npm audit --audit-level=high || true
      
    - name: Basic security scan with semgrep
      uses: returntocorp/semgrep-action@v1
      with:
        config: p/security-audit
      continue-on-error: true
      
    - name: Success message
      if: success()
      run: echo "✅ All code review checks passed!"
